Fix smart coupons on redirect flow & display available coupons on embedded checkout page
krokedil/avarda-checkout-for-woocommerce pull request #74
Opened 2024-02-16 12:09 UTC by mntzrr

2024-05-29 06:44 UTC, MichaelBengtsson requested changes

2024-05-29 06:44 UTC, MichaelBengtsson commented on templates/avarda-checkout.php
> +do_action( 'woocommerce_before_checkout_form', WC()->checkout() );
Did we discuss this internally to say this is a OK solution? Wont this possibly make the giftcards show twice for people that have manually added this action themselves?

2024-05-29 06:44 UTC, MichaelBengtsson commented on composer.json
> +        "squizlabs/php_codesniffer": "*"
Why is squizlabs/php_codesniffer added as a separate dependency? Its included as a dependency from [wp-coding-standards/wpcs](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/composer.json#L24) so should not be required to be added directly right?

2024-05-29 06:44 UTC, MichaelBengtsson commented on classes/requests/helpers/class-aco-helper-cart.php
> -					);
Are we removing support for Smart Coupons? I only see the WCGiftCards plugins compatibility class being used.

2024-05-29 06:44 UTC, MichaelBengtsson commented on classes/requests/helpers/class-aco-helper-order.php
> -				}
Are we removing support for Smart Coupons? I only see the WCGiftCards plugins compatibility code being used.

2024-05-29 07:38 UTC, MichaelBengtsson commented on classes/requests/helpers/class-aco-helper-cart.php
> -					);
Ignore this, i read the code wrong

2024-05-29 07:38 UTC, MichaelBengtsson commented on classes/requests/helpers/class-aco-helper-order.php
> -				}
Ignore this, read the code wrong

2024-05-29 19:44 UTC, mntzrr commented on templates/avarda-checkout.php
> +do_action( 'woocommerce_before_checkout_form', WC()->checkout() );
This was not intentional. I had it to display the coupon on the checkout page. I'll remove it.

2024-05-31 09:25 UTC, MichaelBengtsson approved these changes

2024-06-13 07:38 UTC, merged