Add support for integrated WooCommerce shipping
krokedil/avarda-checkout-for-woocommerce pull request #87
Opened 2024-08-29 11:29 UTC by MichaelBengtsson

* Feature - Adds support for adding WooCommerce shipping methods inside Avarda Checkout. This is required to be configured with Avarda before enabling.
* Feature - Add setting to show order line items in the Avarda Checkout directly.
* Fix - Fixed an issue with attempting to pass an empty customer object to Avarda causing it to be sent incorrectly triggering a error.
* Tweak - Changed the setting for integrated shipping from a checkbox to a select to switch between None, WooCommerce and Partner integrated shipping.

2024-10-07 09:13 UTC, mntzrr requested changes

2024-10-07 09:13 UTC, mntzrr commented on classes/requests/helpers/class-aco-helper-checkout-setup.php
> +		$checkout_setup['displayItems'] = 'yes' === $avarda_settings['display_items'] ?? 'no';
I think this is what you meant:

```php
'yes' === ( $avarda_settings['display_items'] ?? 'no' )
```

Otherwise, it will never evaluate to `null`, and thus never default to `'no'` since the Boolean expression will take precedence, resulting in potentially an undefined index warning.

2024-10-09 09:05 UTC, MichaelBengtsson commented on avarda-checkout-for-woocommerce.php
> +			}
Yes this is intentional. This will let the WC setting override the previous setting after combining them.

2024-10-11 12:08 UTC, mntzrr approved these changes

2024-10-11 12:47 UTC, merged