Use get_instance_id for WC_Shipping
krokedil/avarda-checkout-for-woocommerce pull request #92
Opened 2024-09-18 15:57 UTC by anyakro

Use get_instance_id() for WC_Shipping instead of get_id()

2024-09-19 08:22 UTC, mntzrr requested changes

2024-09-19 08:22 UTC, mntzrr commented on classes/requests/helpers/class-aco-helper-cart.php
> +				if ( $chosen_shipping === $rate->get_instance_id() ) {
Based on the Woo documentation, a `WC_Shipping_Rate` should have a [`get_id`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Rate.html#method_get_id) method.  Since this is not available, which class is `$rate` an instance of?

I would suggest combining [`get_method_id`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Rate.html#method_get_method_id) with [`get_instance_id`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Rate.html#method_get_method_id), if `get_id` doesn't exist.

```php
$rate->get_method_id() . ':' . $rate->get_instance_id();
```

2024-09-19 08:22 UTC, mntzrr commented on classes/class-aco-checkout.php
> +		if ( false === strpos( $rate->get_instance_id(), 'aco_shipping' ) ) { // Explicitly check for false, as strpos can return 0.
I would suggest combining [`get_method_id`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Rate.html#method_get_method_id) with [`get_instance_id`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Rate.html#method_get_method_id), if `get_id` doesn't exist.

```php
$rate->get_method_id() . ':' . $rate->get_instance_id();
```

2024-09-19 14:00 UTC, anyakro commented on classes/requests/helpers/class-aco-helper-cart.php
> +				if ( $chosen_shipping === $rate->get_instance_id() ) {
You're right, and for me $rate _is_ an instance of WC_Shipping_Rate which makes me not able to replicate this. 

In his error, $rate is of course (for some reason) an instance of WC_Shipping_Flat_Rate. Perhaps this is the core issue that I should explore further?

Regarding the $rate->get_method_id() . ':' . $rate->get_instance_id(): I think that this might not work in his case, as [WC_Shipping_Flat_Rate does not seem to have get_method_id](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Flat-Rate.html)?

Since it does however have get_instance_id, perhaps I could simply check if the get_id method exists for $rate, and if not, instead simply check get_instance_id? In the case that the shifting classes used for $rate is normal/expected behavior :)

2024-09-20 12:13 UTC, mntzrr commented on classes/requests/helpers/class-aco-helper-cart.php
> +				if ( $chosen_shipping === $rate->get_instance_id() ) {
According to the documentation, `WC_Shipping_Flat_Rate` should have a [`get_rate_id()`](https://woocommerce.github.io/code-reference/classes/WC-Shipping-Method.html#method_get_rate_id) since it inherits from `WC_Shipping_Method` which you could use instead.

> Returns a rate ID based on this methods ID and instance, with an optional suffix if distinguishing between multiple rates.


So check if you have a `get_rate_id` first, and if it isn't available, construct it yourself using `get_method_id` and `get_instance_id`. However, I am not sure in which order they appear in  if you use `get_rate_id` (method id first or instance id first), so please verify this.

2024-09-25 08:32 UTC, anyakro commented on classes/requests/helpers/class-aco-helper-cart.php
> +				if ( $chosen_shipping === $rate->get_instance_id() ) {
Like this? Logged the order of get_id, `get_method_id` followed by `get_instance_id` should be correct.

2024-09-25 21:54 UTC, mntzrr approved these changes

2024-09-25 21:54 UTC, merged